### ISSUE TITLE
dialog提示文字显示有缺陷

### ISSUE THREAD

**Issue by celverbamboo** [didi/cube-ui#339]
![screenshot_20181020-115247](https://user-images.githubusercontent.com/24216880/47251197-81d6f800-d463-11e8-8865-56b0db0b8ed9.jpg)

**Comment by theniceangel** [comment]
这是在安卓机上？

**Comment by dolymood** [comment]
部分机型是有这样的问题，可以先把 

```css
.cube-dialog-title-def {
  overflow: hidden;
}
```

把这个样式覆盖掉：

```css
.cube-dialog .cube-dialog-title-def {
  overflow: visible;
}
```
