### ISSUE TITLE
系统内的h1 h2 h3等标签的默认样式都不生效

### ISSUE THREAD

**Issue by hellolex** [didi/cube-ui#752]
移动端有部分页面内容是在其他系统的富文本编辑器录入的，但是在cubeui中显示的话发现简单的h1 h2 h3 b之类的标签都无法正常显示
查看了下样式代码发现cubeui默认定义了这些标签的font-size:100%，导致标签的默认样式无法显示

**Comment by dolymood** [comment]
这个是我们之前设计初期场景限制导致的
解法的话 就是 把这些默认样式覆盖成你想要的

例如

```css
html h1,
html h2,
html h4,
html b {
font-size: 100%; // or inherit
}
```
